### ISSUE TITLE
Mouse position issue

### ISSUE THREAD

**Issue by xChaosityx** [parsiad/nexus-autodl#1]
OS: Windows 10
Display resolution: 1920 x 1080
Refresh rate: 60
Monitors: 3 (All 1920 x 1080)

I'm having an issue where sometimes the program will get stuck on trying to click on "Choose download type" in the download page Instead of clicking slow download or click here and will seemingly hang forever until I restart the program, this seems to happen randomly.

I was able to "Fix" the issue by placing the wabbajack program GUI half way between my monitors so that the "Choose download type" text was not visible on my primary monitor, Since it only seems to be able to view my primary monitor and not my side monitors.

**Comment by xChaosityx** [comment]
Update: A mod named MCM helper caused it to hang, It was trying to click on MCM helper forever

**Comment by parsiad** [comment]
Thank you for your bug report. Can you provide a lossless (e.g., PNG) screenshot of the screen it has issues with? It will help with debugging.

**Comment by xChaosityx** [comment]
![image](https://user-images.githubusercontent.com/62197109/176357344-e0a8d493-8098-4fe7-a3ec-7ce31355e997.png)

**Comment by parsiad** [comment]
It tries to click on the Wabbajack window?

**Comment by xChaosityx** [comment]
No, when Wabbajack automatically opens a nexus mods download page, it scrolls down the page to where you can click "Slow download" and "Fast download" Sometimes it will get stuck on trying to click on "Choose download type"

I would assume your using some form of image recognition, If that's the case I believe it needs to be edited to require more of an exact match before it tries to click, Or after each time it tries to click, it scans again and tries to click any other matches it finds

**Comment by parsiad** [comment]
To clarify, I was asking if you could share a screenshot of the page it gets stuck on (not the Wabbajack page). Can I trouble you for that? It is likely rendered differently on your computer and it would help in making the image detection more robust.

> I would assume your using some form of image recognition

Correct. You can look at the source code (it's very short) if you are curious.

**Comment by xChaosityx** [comment]
Ah my bad! I attached an image of what it got stuck on
![image](https://user-images.githubusercontent.com/62197109/176572219-e8371396-b5e5-41b8-a8a7-95631f02934c.png)

**Comment by parsiad** [comment]
This may have been fixed by #6. Please download the binary and let me know if it works. I will close the issue for now, but feel free to reopen it if not.
