### ISSUE TITLE
Download buttom clicking on previus buttom

### ISSUE THREAD

**Issue by RodrigoRamone7** [parsiad/nexus-autodl#14]
After i execute the program, the download page works fine, but after his click on slow download the program click on previus download buttom. the program click on download after the vortex refresh the download buttom causin the erro messenge of download again the previus mod

**Comment by RodrigoRamone7** [comment]
i have to cancel and click on download to the program click on slow download for me again

**Comment by parsiad** [comment]
Can you include screenshots indicating the failure mode?
