### ISSUE TITLE
Not working on Nexus Mod Manager but working on browser

### ISSUE THREAD

**Issue by aviesinar** [parsiad/nexus-autodl#15]

**Comment by parsiad** [comment]
Can you include screenshots indicating the failure mode?

**Comment by mr0driguez** [comment]
Hey, I can't push changes but I fixed it with a new image of the download button. The whole thing worked with this image. Just add it to the templates folder.
![4_30_vortex_download](https://user-images.githubusercontent.com/3464635/224441490-7a8979d8-8536-4ae6-b229-0c827ba559c7.png)

**Comment by JamisonBice** [comment]
Just tried it and it actually works either Nexus changed the button or the image is just slightly upscaled but yea I also removed the click here button to remove duplicate big downloads. Had to do 6 pip installs for python to even get it to make though just in case anyone else runs into that.

**Comment by Vaakaja** [comment]
Having the same problem but im too fucking stupid to figure out how to do the fixes, or how to change anything

**Comment by Xayayia** [comment]
can someone push fixed version?

**Comment by BanWolf** [comment]
I have the same problem, how to fix it?

**Comment by parsiad** [comment]
There is a new release; please consider updating.
