### ISSUE TITLE
Why does it only work on the browser slow download and not on the vortex collection download?

### ISSUE THREAD

**Issue by ghost** [parsiad/nexus-autodl#16]
I have to manually click the vortex download button but it did auto click the browser download but not without it auto clicking the browser again to download the second time

**Comment by parsiad** [comment]
Is [this](https://user-images.githubusercontent.com/8885794/210198651-42de3141-e303-4679-8ef9-49c96d0e50ff.png) page you are talking about? If so (please confirm), support for this was added in [this PR](https://github.com/parsiad/nexus-autodl/pull/11). the master branch on GitHub is more recent than the binary EXE on the release page. If not, can you include screenshots indicating the failure mode?

**Comment by ghost** [comment]
Yes it is the page (https://user-images.githubusercontent.com/8885794/210198651-42de3141-e303-4679-8ef9-49c96d0e50ff.png), i guess i was under the misconception that the exe file is also updated to work on vortex. Thank you for your time

**Comment by megaxayda2** [comment]
Could you send me an updated exe? I can't get the script working for some reasons
![Screenshot (179)](https://user-images.githubusercontent.com/125480103/219284753-5d391102-27ca-446e-b347-e73f40c66274.png)

**Comment by ghost** [comment]
bad news, the script still doesn't click the vortex download, it clicked the download in the TEMPLATE files instead 
![Screenshot (188)](https://user-images.githubusercontent.com/125480103/219381500-0569c9f4-6c97-47ee-a901-44e9e2b63f97.png)
![Screenshot (189)](https://user-images.githubusercontent.com/125480103/219381510-6ba96352-e64a-40d6-ab00-66f5f7ebfeb7.png)

**Comment by parsiad** [comment]
It searches for the thing on your screen that looks most like the image in the templates directory. In this case, it's finding the thumbnail of the image it's searching for. The solution is simple: close explorer or navigate away from the templates directory.

**Comment by ghost** [comment]
i've already ran it many times before i was even aware of the templates files or have stepped in it (https://screenrec.com/share/AvfFHPhyM1)

**Comment by ghost** [comment]
i have managed to get it working by replacing the one in the templates files with my own screenshot download button

**Comment by parsiad** [comment]
Could you share the image you used in the templates directory?

**Comment by ghost** [comment]
![3_30_vortex_download](https://user-images.githubusercontent.com/125480103/219820010-166791fe-b92f-4387-b586-0a8156899666.png)
