### ISSUE TITLE
"Click here to continue" feature doesn't work

### ISSUE THREAD

**Issue by olivergus** [parsiad/nexus-autodl#19]
![image](https://user-images.githubusercontent.com/13122113/231318838-0ada6955-3e90-4b58-92ac-6a66b30305ac.png)

It tries to click forever on that.
I also tried with my Jitbit Macro Recorder, it sometimes works, sometimes doesn't. Perhaps something on my end?

**Comment by parsiad** [comment]
There is a new release; please consider updating.
