### ISSUE TITLE
'Download' button in Vortex's Collection Download Confirmation Menu doesn't get clicked on properly

### ISSUE THREAD

**Issue by Evil-Operative** [parsiad/nexus-autodl#20]
Instead, it clicks here:
![image](https://user-images.githubusercontent.com/39020792/232312997-400bc63c-8485-42ad-af6f-654f1d5e515d.png)

For the record, I'm using the .py script from the github website itself, and not the release .exe uploaded on the other website.

**Comment by BanWolf** [comment]
I have the same problem.

**Comment by tensor5g** [comment]
same problem

**Comment by ThePhaseless** [comment]
if you're using py files, just replace 3_30_vortex_download file in templates folder with your own screenshot (make screenshot with a bit of background to avoid missclicks)

**Comment by Evil-Operative** [comment]
> if you're using py files, just replace 3_30_vortex_download file in templates folder with your own screenshot (make screenshot with a bit of background to avoid missclicks)

This didn't work for some reason. I tried

**Comment by dnt400311** [comment]
> ###
> **[ThePhaseless](/ThePhaseless) ** commented [May 18, 2023](#issuecomment-1553262447) •

why does my .py file open the cmd and closes instantly?

**Comment by ThePhaseless** [comment]
@dnt400311 Your question is not connected with this issue, please open a new one, but first try running it from terminal like this: ```python3 scriptname.py```

**Comment by Ireheart** [comment]
> > **[ThePhaseless](/ThePhaseless) ** commented [May 18, 2023](#issuecomment-1553262447) •
> 
> why does my .py file open the cmd and closes instantly?

Because author does not include dependencies like numpy.

See https://github.com/greg-ynx/NexusDownloadFlow-2022 as alternative

**Comment by parsiad** [comment]
There is a new release; please consider updating.
