### ISSUE TITLE
Can someone just fix the download button?

### ISSUE THREAD

**Issue by dnt400311** [parsiad/nexus-autodl#21]
the script doesn't hit the download button. that's a problem. needs fixing. there is no clear explanation for people that know nothing about coding on how to fix it.

**Comment by hmmR0E** [comment]
the download button can't be recognized by the exe and the application doesn't have any asset folder to replace the file so you have to run the repo yourself but the repo itself has errors like the asset "numpy" which is not included in the repository.

so try checking out https://github.com/greg-ynx/NexusDownloadFlow-2022  as alternative, just do the instrucstions for the first 2 template and replace the template 3 with the "Download" button on vortex.

**Comment by hmmR0E** [comment]
> the script doesn't hit the download button. that's a problem. needs fixing. there is no clear explanation for people that know nothing about coding on how to fix it.

the download button can't be recognized by the exe and the application doesn't have any asset folder to replace the file so you have to run the repo yourself but the repo itself has errors like the asset "numpy" which is not included in the repository.

so try checking out https://github.com/greg-ynx/NexusDownloadFlow-2022  as alternative, just do the instructions for the first 2 template and replace the template 3 with the "Download" button on vortex.

**Comment by parsiad** [comment]
The application looks for images in the `templates/` directory. You can fill the `templates/` directory with your own screenshots of the download button since it may be rendered differently (e.g., different font) on each machine.

Also, there is a new release; please consider updating.
