### ISSUE TITLE
Rapidgator? Seriously?

### ISSUE THREAD

**Issue by WayneDwane** [parsiad/nexus-autodl#24]
Tons of sites out there you could've uploaded this,and you HAD to choose that piece of garbage. Fuck's sake.

**Comment by Kickskii** [comment]
> Tons of sites out there you could've uploaded this,and you HAD to choose that piece of garbage. Fuck's sake.

i put together a build on my forked repo 
hopefully that helps out since author isnt hosting on github for some reason

**Comment by Semiotikal** [comment]
Yeah this is rather sketchy. Why upload it on rapidgator?

**Comment by mrgodotuser** [comment]
why not just download the branch and run it from source?

**Comment by parsiad** [comment]
There is a new release on GitHub now.
