### ISSUE TITLE
file upload is broken and the website is unusable

### ISSUE THREAD

**Issue by Bluenochian** [parsiad/nexus-autodl#31]
the website where the file is uploaded requires premium and if you do not have it and if it's bugged for a second, then it'll ask you to wait for 1 hour then 2 hours after that for no reason, and then a full day and the cycle repeats, there are sooo many normal, non-premium, or just not-so-broken uploading platforms, for god's sake, please upload it somewhere else.

**Comment by EntangledConception** [comment]
if we could get a mirror or just it release via github thatd be great

**Comment by parsiad** [comment]
There is a new release on GitHub now.
