### ISSUE TITLE
Does not click the download button on Vortex Collections

### ISSUE THREAD

**Issue by Yurrrrrrski** [parsiad/nexus-autodl#34]
im a whole scrub to the fallout 4 modding scene but im trying to download the A storywealth mod collection via vortex but nexus autodl is not working it only works when i click the download popup and then it switches to the download page in the browser  
![Capture](https://github.com/parsiad/nexus-autodl/assets/170263702/b4500b83-ec4f-4c91-81a9-09d2a9c7dc72)
anyway where i can fix this so i dont have to sit on my ass every 5 minutes just to click a singular mod download

**Comment by parsiad** [comment]
There is a new release; please consider updating.
