### ISSUE TITLE
only wants to click one download button

### ISSUE THREAD

**Issue by MagicWade1** [parsiad/nexus-autodl#36]
Im attempting to download a mod collection through vortex mod manager. On vortex I need to click "download" every time I want to download another mod in the collection. The n the mod manager takes me to the nexus mod page where I need to click "slow download". No where to problem comes in is the bot wants to click the vortex download button even when the nexus slow download button is up. Thus, the bot opens up several tabs for the same mod without actually installing it. is their any way to fix this perhaps a delay or a way to tell it and order to click in?

**Comment by parsiad** [comment]
Templates are now sorted by filename. I rolled a new release including this change: https://github.com/parsiad/nexus-autodl/releases/tag/0.2.1

**Comment by GnomeBeans** [comment]
I continue having this issue. I name screenshots A and B. It loads both but the script will only ever use A and not move on. I also use --confidence 0.9 or it never clicks anything. EDIT: Renaming the files A1 and B1 has fixed.
