### ISSUE TITLE
getting an error trying out new build

### ISSUE THREAD

**Issue by Kickskii** [parsiad/nexus-autodl#38]
trying to open the built exe from releases gives me this error

```Traceback (most recent call last):
File "\\WBoxSvr\shared\nexus-autodl\nexus_autodl.py", line 90, in <module>
File "click\core py", line 1157, in ＿call＿
File "click\core.py", line 1078, in main
File "click\core.py", line 1434, in invoke
File "click\core.py", line 783, in invoke
File "\\VBoxSvr\shared\nexus-autodl\nexus_autodl.py", line 45, in main
File "\\VBoxSvr\shared\nexus-autodl\nexus_autodl.py", line 27, in human_sorted
File "pathlib.py", line 1056, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: "D:\\Common_Folders\\Downloads\\\Programs\\tem
plates'
[12620] Failed to execute script 'nexus_autodl' due to unhandled exception!```

more or less flashes for a moment and then closes

**Comment by Kickskii** [comment]
launching the exe from terminal works but I don't get the first start steps that it should have asked for that I noticed from reading the refactored code

edit: nevermind this i was accidentally launching the old exe that i built instead of the refactored one from your repo  heres an image
![image](https://github.com/parsiad/nexus-autodl/assets/56576955/6120b4e4-49e1-409b-bac3-c79dae3d6a00)

**Comment by Kickskii** [comment]
found a fix to the above, a folder named "template" needs to exist where the new exe is, if not then it will panic and close, a workaround for it is checking for a template directory and then making one if it doesnt exist before showing the messege about dropping a screenshot of the download button in the template directory

it should also maybe tell you that it made the directory for you if it didnt exist already, and a one time messege like "loaded template from template directory" before running if the image was loaded(ofc the other messege wont be shown if an image was loaded)

**Comment by Kickskii** [comment]
lastly thank you for the update ❤️

**Comment by parsiad** [comment]
Fixed.
