### ISSUE TITLE
How do i make this work?

### ISSUE THREAD

**Issue by ZORXdsh** [parsiad/nexus-autodl#39]
I just downloaded the 0.2.1 version and double-clicked on the download file "nexus_autodl.exe" a CMD page opened after 2-3 seconds it closed and nothing happened after that.
![Screenshot 2024-06-12 121815](https://github.com/parsiad/nexus-autodl/assets/77897109/e253dacf-e745-4228-846c-7bea04b93db2)

I've tried:
running it as an administrator
moving the .exe file to the same location as the Wabbajack.exe
redownloading nexus_autodl
downloading and running nexus_autodl 0.2.0
downloading all of the assets and moving the nexus_autodl.exe to its extracted location

**Comment by parsiad** [comment]
Make a `templates` directory in the path specified in the error message. This is a known issue; see https://github.com/parsiad/nexus-autodl/issues/38#issuecomment-2152083063
