### ISSUE TITLE
mouse going to the center of the screen

### ISSUE THREAD

**Issue by Thiago-Caffaro** [parsiad/nexus-autodl#40]
when i run it, it macthes the srceen, but my mouse olny goes to the center of the screen

**Comment by kirariki** [comment]
you need template where it only focus the download only not the center of the screen

**Comment by mark522412** [comment]
> you need template where it only focus the download only not the center of the screen

How? when i press PrintScreen to get the screen shot it wont get the mouse pointer. or you mean put the download on the center of screen shot? how you do that? or you mean something else?

Edit: sorry got it thanks. i realized i have to crop only the download button. i was putting the whole picture. im dumb lol

**Comment by kirariki** [comment]
just screen shot the download button with win+shift+S i hope you understand
and we can close this issue, before it get notice.....
