### ISSUE TITLE
Prompt just disappear without doing nothing

### ISSUE THREAD

**Issue by bellbill** [parsiad/nexus-autodl#41]
I've tried everything, run as admin, create a "template" folder, putting it in every drive I have, even in Vortex folder, running as admin... It just closes so fast I can't even read whats written in the prompt window.

**Comment by Thiago-Caffaro** [comment]
[https://github.com/parsiad/nexus-autodl/issues/39#issuecomment-2164333112](url)

**Comment by Thiago-Caffaro** [comment]
#39

**Comment by parsiad** [comment]
You can open a terminal and run the exe from the terminal instead of double clicking on it.
