### ISSUE TITLE
Opening premium Nexus subscription page

### ISSUE THREAD

**Issue by bellbill** [parsiad/nexus-autodl#42]
So I made the autodl work but It opens always the nexus page where you can subscribe... (https://users.nexusmods.com/account/billing/premium?utm_medium=vortex&utm_source=header_ad&utm_campaign=buy_premium)... Any idea why It does that?

**Comment by Marcksvel** [comment]
Same deal. My assumption is that "Go premium" button on vortex is similar to "download" so script is also clicking that

**Comment by parsiad** [comment]
Try running the script with a higher confidence parameter. For example,
```
--confidence 0.9
```
