### ISSUE TITLE
Close tab after install

### ISSUE THREAD

**Issue by ysssssn** [parsiad/nexus-autodl#43]
Is there any way to close the chrome tab after a mod is installed? When downloading a collection through vortex, the tab is opened on chrome instead of a separate one that auto closes like in Wabbajack, so I need to manually close it after every mod so my PC won't blow up.

**Comment by parsiad** [comment]
You can solve this with a Chrome extension https://chromewebstore.google.com/detail/xtab/amddgdnlkmohapieeekfknakgdnpbleb
