### ISSUE TITLE
it close after few sec

### ISSUE THREAD

**Issue by AlexiasUnknown** [parsiad/nexus-autodl#44]
idk why it close after few seconde it have an error 

https://github.com/parsiad/nexus-autodl/assets/173878598/cf15bf80-42c3-4e1a-b71c-e7bb89678f10

**Comment by Vikyek** [comment]
same...

**Comment by lyingsackoffun** [comment]
You must make a templates folder in the directory you placed the exe in. 

https://github.com/parsiad/nexus-autodl/issues/38
