### ISSUE TITLE
Running application

### ISSUE THREAD

**Issue by blazeftp** [parsiad/nexus-autodl#49]
Hi. 
Having some trouble getting this to run. 

Downloaded the nexus-autodl-0.2.1 folder and placed the Nexus auto DL inside and created a templates folder.
Ran the application. 

Then placed the templates from assets inside. Re-ran the application

Nothing is happening. 

Can someone confirm what I am doing wrong ? 

Thanks for creating this tool. Very helpful and hopefully can get it working !

**Comment by parsiad** [comment]
If you [run it from the command line](https://superuser.com/questions/876933/running-exe-in-command-prompt), you will get an error you can paste here.

**Comment by blazeftp** [comment]
![image_2024-07-31_210006333](https://github.com/user-attachments/assets/73cf2c73-9d28-4b09-b73b-b9a1a61836cb)


I managed to grab this before the window closed. 


![image_2024-07-31_210152785](https://github.com/user-attachments/assets/c525bdf0-3319-49b6-a6d6-f4b3fb1550fd)

This is where i have all the files set up.

Thanks for taking the time to help.

**Comment by parsiad** [comment]
It looks like it expects the templates directory to be at `C:\Users\Ryanl\templates`. Can you make it there?

**Comment by blazeftp** [comment]
> It looks like it expects the templates directory to be at `C:\Users\Ryanl\templates`. Can you make it there?

That was my first thought but apparently there is already a folder there called templates but its hidden by Microsoft. going to move the files to another hard drive see if it changes the directory it asks for.

**Comment by lucifercannibal** [comment]
> > It looks like it expects the templates directory to be at `C:\Users\Ryanl\templates`. Can you make it there?
> 
> That was my first thought but apparently there is already a folder there called templates but its hidden by Microsoft. going to move the files to another hard drive see if it changes the directory it asks for.

Same issue here

**Comment by blazeftp** [comment]
> > > It looks like it expects the templates directory to be at `C:\Users\Ryanl\templates`. Can you make it there?
> > 
> > 
> > That was my first thought but apparently there is already a folder there called templates but its hidden by Microsoft. going to move the files to another hard drive see if it changes the directory it asks for.
> 
> Same issue here

I re-downloaded and moved it to my storage drive and it bypassed this issue.

**Comment by blazeftp** [comment]
> It looks like it expects the templates directory to be at `C:\Users\Ryanl\templates`. Can you make it there?

Managed to find a work around and get it up and running but both are stuck on trying to find the images. 

I have both applications split it 50/50 on screen and screen shot each side and labelled it according to the template in the folder. 

![image_2024-07-31_221309245](https://github.com/user-attachments/assets/19ff2994-a70c-49f1-a504-596b3051f85b)

**Comment by parsiad** [comment]
You can specify `--templates-path` as well.

As for your separate issue, you can play with the `--confidence` flag.

**Comment by blazeftp** [comment]
I placed it inside the nexus-autodl-0.2.1 folder but moved it from my SSD to my HDD to avoid the first issue.

**Comment by AmeliaLotus** [comment]
Yeah this problem is fixed just by adding a "templates" folder where you put the .exe ... So like C:/Users/Parsiad/AutoDL/templates and make sure the Auto DL exe is inside the AutoDL folder.

**Comment by Laxuard** [comment]
where is the autodl folder ?? i want to download it myself and when i run the exe for the first time there is no instructions

**Comment by parsiad** [comment]
A new release is available with a GUI that may be more intuitive.

The GUI allows you to select the templates folder.
