### ISSUE TITLE
Just started using this, I only have 1 issue with it so far

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [parsiad/nexus-autodl#51]
Hi! I just started using this and it's been very helpful but it has at least one issue. I only have a template for it to click slow download, but for some reason if a donation page shows up, it also clicks on donate. Because of this, it's gotten stuck quite a few times and I've had to close pages upon pages of PayPal pages it's opened. I don't know why it does this but would it be possible to fix that?

Edit: it now keeps clicking go premium and won't stop

**Comment by parsiad** [comment]
See https://github.com/parsiad/nexus-autodl/issues/42
