### ISSUE TITLE
Unhelpful/Broken

### ISSUE THREAD

**Issue by AnonDragonWolfess** [parsiad/nexus-autodl#52]
I really don't get it, and I'm at my wit's end. This thing is supposed to give instructions, but it skips the instructions entirely!

I downloaded the binary, and when I double click on it, I get a warning from my computer. I ignore the warning, and it immediately skips the instructions and opens the terminal. What am I doing wrong???

**Comment by parsiad** [comment]
A new release is available with a GUI that may be more intuitive.
