### ISSUE TITLE
Virtual machine

### ISSUE THREAD

**Issue by kirariki** [parsiad/nexus-autodl#56]
So lets say . Currently this program doesn't doesn't support alt tab Or minimize right?,
I have an idea where the virtual machine come in?

Currently im trying to researching how to mount the drive directly to download folder intead of exporting it..

**Comment by kirariki** [comment]
Sadly virtualbox cant support mouse on alt tab yet...

**Comment by parsiad** [comment]
I don't understand your original post. Can you explain your problem more clearly?

**Comment by kirariki** [comment]
oh im sory .
im tring to make , the program can run in background while , i do other stuff,
sadly since virtual box almost not (kinda) support the script it while you minimize virtual box.

**Comment by kirariki** [comment]
sory to bother you..

**Comment by parsiad** [comment]
I believe the tkinter window can run minimized. Perhaps I still do not understand your meaning?

**Comment by kirariki** [comment]
oh it not the tkinter but the virtual box im minimize it, but then again im done with this issue thx tho for your help
