### ISSUE TITLE
keeps clicking donate and premium membership buttons on nexus download when using wabbajack

### ISSUE THREAD

**Issue by Yurrrrrrski** [parsiad/nexus-autodl#57]

**Comment by parsiad** [comment]
Try taking a smaller screenshot around the item you want clicked and/or increasing the confidence parameter.

**Comment by inteltium** [comment]
I found a solution that works for me:
Open a blank text document and force it to stay above other windows, then block out the "get premium" button with it. To force the text document to stay on top, I installed windows Powertoys, then pressed Win+Ctrl+T on it. I'm sure any other window would work to block the button, but a blank text file is free of text.
