### ISSUE TITLE
Clicking on get premium. 

### ISSUE THREAD

**Issue by inteltium** [parsiad/nexus-autodl#58]
Amazing tool, only issue is it seems like Nexus know what this is - It directs the cursor to the get premium button. I've tried changing resolution. 

Had more success with NexusDownloadFlow.

**Comment by parsiad** [comment]
Try taking a smaller screenshot around the item you want clicked and/or increasing the confidence parameter.

**Comment by inteltium** [comment]
Turns out NexusDownloadFlow was doing the same thing - auto clicking on" donate" or "get premium."

I found a solution that works for me:
Open a blank text document and force it to stay above other windows, then block out the "get premium" button with it. To force the text document to stay on top, I installed windows Powertoys, then pressed Win+Ctrl+T on it. I'm sure any other window would work to block the button, but a blank text file is free of text.

Thanks, this clicker is really great.
